### ISSUE TITLE
aarch里面的库文件有x86对应的吗

### ISSUE THREAD

**Issue by Nicloeccc** [Ranorle/Yolov5-react-pedestrian-flow-monitoring-system#1]

**Comment by Ranorle** [comment]
该项目默认使用Linux的aarch64的snpe库，如需要其他平台和硬件（如x86）的高通snpe库文件，请前往高通官网https://qpm.qualcomm.com/#/main/tools/details/qualcomm_neural_processing_sdk 下载对应版本并替换
